export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
export const API_REQUEST = 'API_REQUEST';
export const API_REQUEST_SUCCEEDED = 'API_REQUEST_SUCCEEDED';
export const API_REQUEST_FAILED = 'API_REQUEST_FAILED';
export const API_REQUEST_LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export const API_REQUEST_SUCCEEDED_LOGIN = 'API_REQUEST_SUCCEEDED_LOGIN';

// user search action types
export const API_REQUEST_SEARCH_USER = 'API_REQUEST_SEARCH_USER';
export const API_REQUEST_SUCCEEDED_SEARCH_USER = 'API_REQUEST_SUCCEEDED_SEARCH_USER';
export const API_REQUEST_FAILED_SEARCH_USER = 'API_REQUEST_FAILED_SEARCH_USER';

